name: pps-mw-training
channels:
  - conda-forge
  - defaults
  - nsidc

dependencies:
  - python=3.10
  - graphviz
  - h5py
  - matplotlib
  - netcdf4
  - numpy
  - pydot
  - pyproj
  - tensorflow
  - xarray
