name: pps-mw-training
channels:
  - conda-forge

dependencies:
  - python=3.10
  - dask
  - graphviz
  - h5py
  - matplotlib
  - netcdf4
  - numpy
  - psutil
  - pydot
  - pyproj
  - tensorflow
  - xarray
